server:
  listen: 8080
  host: localhost
  root: www
  client_max_body_size: 2G
  server_name: test
#/testetst
#/about/gf/ forlder1/forlder2/file.txt ---> www/forlder1/forlder2/file.txt
#/about/gf/forlder1  --> www/forlder2/file.txt
  location:
    - path: /about/gf
    - root:  www
    - listing_dir: on
    - upload: on
    - autoindex: off
    - methods:  POST GET
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
  location:
    - path: /home
    - root:  www
    - upload: on
    - listing_dir: on
    - autoindex: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
   location:
    - path: /
    - root:  www
    - upload: on
    - autoindex: off
    - listing_dir: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash

server:
  listen: 8080
  host: localhost
  root: www
  client_max_body_size: 1G
  server_name: localhost

  location:
    - path: /about
    - root:   www
    - upload: on
    - autoindex: on
    - listing_dir: on
    - methods: POST GET
  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: off
    - listing_dir: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php
    - cgi_path: .sh, /usr/bin/bash

server:
  listen: 8081
  host: localhost
  root: www
  client_max_body_size: 1G
  server_name: test

  location:
    - path: /about
    - root:   www
    - upload: on
    - autoindex: on
    - listing_dir: off
    - index:  index.html
    - methods: GET
  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: on
    - listing_dir: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php
    - cgi_path: .sh, /usr/bin/bash
