server:
  listen: 8080
  host: localhost
  root: www
  client_max_body_size: 1G
  server_name: example.com

  location:
    - path: /about/gf
    - listing_dir: on
    - upload: on
    - autoindex: off
    - methods:  POST GET
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
  location:
    - path: /home
    - root:  www
    - upload: on
    - listing_dir: on
    - autoindex: off
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
   location:
    - path: /
    - root:  www
    - upload: on
    - autoindex: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash

server:
  listen: 8081
  host: localhost
  root: www
  client_max_body_size: 2G
  server_name: test

  location:
    - path: /about
    - root:   www
    - upload: on
    - autoindex: on
    - listing_dir: on
    - methods: GET POST
  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
