server:
  listen: 8080
  host: localhost
  root: www/1
  client_max_body_size: 1G
  server_name: example.com
  error_page: 404 index.html

  location:
    - path: /about
    - listing_dir: on
    - upload: on
    - autoindex: off 
    - methods:  POST
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
    - return: https://www.google.com
  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash

server:
  listen: 8081
  host: localhost
  root: www/2
  client_max_body_size: 1G
  server_name: test

  location:
    - path: /about
    - root:   www
    - upload: on  
    - autoindex: on
    - methods: GET
  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash