server:
  listen: 8080
  host: 127.0.0.1
  root: www
  client_max_body_size: 1G
  server_name: server1

  location:
    - path: /loc
    - root: www
    - listing_dir: on
    - upload: on
    - upload_path: /upload
    - autoindex: off
    - methods:  POST GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
  location:
    - path: /
    - root:  server1
    - upload: on
    - listing_dir: off
    - autoindex: on
    - upload_path: ./
    - methods: POST
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
   location:
    - path: /dd
    - root:  www
    - upload: on
    - autoindex: off
    - listing_dir: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash

server:
  listen: 8080
  host: 127.0.0.1
  root: www
  client_max_body_size: 1.02G
  server_name: server2

  location:
    - path: /
    - root:  server2
    - upload: on
    - autoindex: on
    - listing_dir: off
    - upload_path: ./
    - methods: POST GET DELETE
    - index: index.html
    - cgi_path: .php, /usr/bin/php-cgi

  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: off
    - listing_dir: on
    - upload_path: upload
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
