server:
  listen: 8081
  host: 127.0.0.8
  root: www/

  location:
    - path: /
    - root:   www
    - upload: on  
    - autoindex: on
    - methods: GET
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
    - proxy_read_time_out: 5s

server:
  listen: 8080
  host: 127.0.0.8
  root: www/

  location:
    - path: /
    - root:   www
    - upload: on  
    - autoindex: on

server:
  listen: 8087
  host: 127.0.0.8
  root: www/

  location:
    - path: /
    - root:   www
    - upload: on  
    - autoindex: on