server:
  listen: 8090
  host: localhost
  root: www
  client_max_body_size: 100319.99B
  server_name: test

  location:
    - path: /loc
    - root: www
    - listing_dir: on
    - upload: on
    - autoindex: off
    - methods:  POST GET
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
  location:
    - path: /
    - root:  www/about/gf
    - upload: on
    - listing_dir: off
    - autoindex: off
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
   location:
    - path: /dd
    - root:  www
    - upload: on
    - autoindex: off
    - listing_dir: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash

server:
  listen: 8080
  host: localhost
  root: www
  client_max_body_size: 1.02G
  server_name: localhost

  location:
    - path: /
    - root:   www
    - upload: on
    - autoindex: on
    - listing_dir: on
    - methods: POST GET
    - cgi_path: .php, /usr/bin/php-cgi

  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: off
    - listing_dir: on
    - upload_path: upload
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
    - return:  https://profile.intra.42.fr/
server:
  listen: 8081
  host: localhost
  root: www
  client_max_body_size: 1G
  server_name: test

  location:
    - path: /about
    - root:   www
    - upload: on
    - autoindex: off
    - listing_dir: on
    - index:  index.html
    - methods: GET
  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: on
    - listing_dir: on
    - methods: POST PUT GET DELETE
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php
    - cgi_path: .sh, /usr/bin/bash
