server:
  listen: 8081
  host: 127.0.0.8
  root: www/1
  client_max_body_size: 1G

  location:
    - path: /test
    - root:  www
    - upload: on
    - autoindex: on
    - methods: POST
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
  location:
    - path: /home
    - root:  www
    - upload: on
    - autoindex: on
    - methods: GET
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash
    - return: https://www.youtube.com/

server:
  listen: 8080
  host: 127.0.0.8
  root: www/2
  client_max_body_size: 1G

  location:
    - path: /
    - root:   www
    - upload: on  
    - autoindex: on
