server:
  listen: 777
  host: 127.0.0.1
  root: www/1

  location:
    - path : /path0
    - root: www
    - upload: on  
    - autoindex: on
    - methods: GET POST
    - index:  index.html
    - cgi_path: .py, /usr/bin/python3
    - cgi_path: .php, /usr/bin/php-cgi
    - cgi_path: .sh, /usr/bin/bash